name: Build & Test

on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - 'docs/**' # Don't run workflow when files are only in the /docs directory

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '5.0.300'
    - name: .NET Build
      run: dotnet build -c Release --nologo
    - name: .NET Test
      run: dotnet test -c Release --no-build --nologo