name: Build, Test & Package

on:
  push:
    branches:
    - main
    paths-ignore:
    - 'docs/**' # Don't run workflow when files are only in the /docs directory

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '5.0.300'
    - name: .NET Build
      run: dotnet build -c Release --nologo
    - name: .NET Test
      run: dotnet test -c Release --no-build --nologo
    - name: .NET Pack
      run: dotnet pack --no-build -c Release --nologo /p:PackageOutputPath=${env:GITHUB_WORKSPACE}\.nupkgs
    - name: Push to GH Packages
      run: dotnet nuget push ${env:GITHUB_WORKSPACE}/.nupkgs/*.nupkg  --source https://nuget.pkg.github.com/deanward81/index.json --api-key ${{ secrets.GITHUB_TOKEN }}